### ISSUE TITLE
Tie in Sphinx document search

### ISSUE THREAD

**Issue by cs2be** [PaddlePaddle/PaddlePaddle.org#109]

**Comment by varunarora** [comment]
How easy or difficult is this to do? Will we be able to tie it in if we aren't going the symlinking mumbo-jumbo we are contemplating?

**Comment by cs2be** [comment]
This is pretty easy to do, I have it working on a stash.  However "book" and "model" is not indexed.  I need to do some research to see if its easy to add these indexes to sphinx search.  Otherwise I can look into a third party full text search engine.

**Comment by varunarora** [comment]
@wangkuiyi For now, do you want the `book` and `models` sections to be indexed by a search feature? @cs2be has been working on getting it working for the main documentation for the new navigation, because Sphinx generates an index for that, but that index doesn't have `book` and `models`.

If we want both of them too, as @cs2be suggests, we'd need to explore third party options like a managed Elastic Search or Algolia.

**Comment by varunarora** [comment]
I think everyone is fine with this for now. Closing.
