### ISSUE TITLE
Separate doc from Paddle repo and make it an independent compiling process

### ISSUE THREAD

**Issue by bobateadev** [PaddlePaddle/PaddlePaddle.org#18]

**Comment by luotao1** [comment]
Do you mean separate [doc](https://github.com/PaddlePaddle/Paddle/tree/develop/doc) outside from the paddle repo?

You may consider the [doc/api](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/api) especially, since all the api-related contents are generated from Paddle source codes in [python/paddle](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle) .

**Comment by varunarora** [comment]
@luotao1 Great!

We have some ideas on how we want to maintain that dependency with the source code modules. Which of the following two ideas do you like better?

1. We take non-doxygen `/doc` dir stuff out of the repo and place it into another repo (with perhaps the contents of `book` and `models`)
2. We leave the Paddle repo contents as is, but pull them in as a git submodule into a new documentation repo (merging all documentation / tutorial related content) and apply custom Sphinx styling on it in this new repo

Would you like to keep bundling the generated docs with the code repo or do you think it's a better idea to split the two out, while making sure we don't break the dependency of code generation from `python/paddle`?

**Comment by luotao1** [comment]
Before I choose the idea, I have some questions:
- Some documents like [build and install](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/getstarted/build_and_install) are different among Paddle version. If we take them out of the repo, how can we keep them consistent with the corresponding Paddle version? (maybe we can generate v0.8.0, v0.9.0 and v0.10.0 in a different way from dev version)
- Some documents like [design](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design) are frequently updated by developers. Since they have a close relationship with the source codes, maybe we can store them in Paddle repo. (But they are not shown on our website currently)

Besides, I am confused that some documents are not shown on our website, such as  [design](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design) and [survey](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/survey). And some other documents are not in doc/, such as [name_convention.md](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/name_convention.md) and [benchmark.md](https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/README.md), et al. Do you have any suggestions about this?

**Comment by varunarora** [comment]
@luotao1 So I think since earlier this week we decided not to touch repo structure. So your right - let's just keep the tie with the existing code.

How do you propose versioning the `doc` dir? Are we using Github releases or do we have a tagging scheme for the same?

**Comment by varunarora** [comment]
@cs2be @luotao1 brings up a good issue of documents that are not showing up on the website - perhaps we should document the idea around updating the navigation so everyone is clear on how to introduce navigational updates based on documentation?

**Comment by luotao1** [comment]
>  Are we using Github releases or do we have a tagging scheme for the same?

You can use Github releases.

**Comment by varunarora** [comment]
Process of updating navigation is awesomely documented by @jetfuel here: https://github.com/PaddlePaddle/PaddlePaddle.org/wiki/sitemap-configurations

**Comment by cs2be** [comment]
Issue has been resolved.  We will continue to build docs from Paddle repo.
