### ISSUE TITLE
The Chinese version of models

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/PaddlePaddle.org#354]
Some chapter of models have README.cn.md. For example, nmt_without_attention has [README.cn.md](https://github.com/PaddlePaddle/models/blob/develop/nmt_without_attention/README.cn.md),  but in http://www.paddlepaddle.org/docs/develop/models/README.cn.html, when I click `8.1 无注意力机制的神经机器翻译`, it still a English version.

**Comment by jetfuel** [comment]
The root README.cn.md (https://github.com/PaddlePaddle/models/blob/develop/README.cn.md) links to topic folders instead of a specific README file. 
For example, 
```
- 1.1 [Hsigmoid加速词向量训练](https://github.com/PaddlePaddle/models/tree/develop/hsigmoid)
- 1.2 [噪声对比估计加速词向量训练](https://github.com/PaddlePaddle/models/tree/develop/nce_cost)
```
And by default, when links to a GitHub folder, it will display README.md file. 

I think it is possible to map the GitHub links to local Models copy folder and check if there is a README.cn.md file. 

Another approach is to update the root README.cn.md in Models, and point to the REAMME file with specific language.

**Comment by luotao1** [comment]
@lcy-seso
> I think it is possible to map the GitHub links to local Models copy folder and check if there is a README.cn.md file.

> Another approach is to update the root README.cn.md in Models, and point to the REAMME file with specific language.
 
which one do you prefer?

**Comment by lcy-seso** [comment]
I prefer the second one. It seems that the latter one is easy to change.

**Comment by luotao1** [comment]
Now, when I click `3.1 Wide & deep 点击率预估模型`, it is a READEME.cn.md file, not an html.

**Comment by jetfuel** [comment]
The issue has been addressed on the develop PaddlePaddle.org branch. We will roll out another release by the end of this week or early next week. Thank you for your patient.

**Comment by jetfuel** [comment]
Fixed.
