### ISSUE TITLE
Website Enhancement Project-5-Adding API mainpage

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#383]
**Website Enhancement Project-5-Adding API main page"**
After enhancement：Click "API" on the top navigation, then jump to the API "main page"
Method: please create an API main page, and paddlepaddle will  add contents ( please see https://github.com/PaddlePaddle/Paddle/issues/8042) on this page.

![image](https://user-images.githubusercontent.com/35982308/35838749-c4b84b3e-0b27-11e8-9e77-46745c06c1f7.png)

The Chinese in the picture says: please add an introduction of paddlepaddle API

**Comment by cs2be** [comment]
@shanyi15 As discussed, It might be more straight forward for Paddle team to create a single "Introduction" page and add it as the first TOC level in Sphinx.  If this is the case, then we can close this issue (Since PPO will automatically pull in that page and make it the first link once Sphinx is updated).

**Comment by shanyi15** [comment]
got this

**Comment by shanyi15** [comment]
@luotao1  Please adding a homepage for API Section, it may be a blank page now, we will adding some introduction of API on this page later.

**Comment by shanyi15** [comment]
please refer to discussion in https://github.com/PaddlePaddle/Paddle/issues/8042
related pr refer to: https://github.com/PaddlePaddle/Paddle/pull/8537
