### ISSUE TITLE
[MLK] Version select

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#494]
Hover the mouse to reveal the dropdown menu. 
The menu should display "V2/V1" with a brief description, and "Fluid" with a brief description

<img width="486" alt="screen shot 2018-06-14 at 3 50 56 pm" src="https://user-images.githubusercontent.com/1093725/41442177-be688a1e-6fea-11e8-8da2-a26e8376ed64.png">

**Comment by varunarora** [comment]
I think this could be a little problematic, because where will we show versions (`0.10.0`, `0.11.0`, etc) then? I think it is much more important to show those, instead of API versions. And then we could default an API against each version, as decided here: https://github.com/PaddlePaddle/Paddle/issues/9859#issuecomment-387230378.

**Comment by captainwoon** [comment]
这里不需要再提供版本的选择了，只需要给出【文档】按钮，点击跳转至【文档页】即可
