### ISSUE TITLE
feedback from users of search engine

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#739]
2 feedbacks
1. type something in search bar, and the explorer becomes frozen
 please have a try, "dropout"is ok, but when we try to type some word begin with "a", after we type "a", it's hard to type the second alphabet

2. after click " show more results" for xxx, the format looks a little bit weird, please see the following pic

![image](https://user-images.githubusercontent.com/35982308/49914010-b480f800-feca-11e8-9898-474a3d6df619.png)

**Comment by varunarora** [comment]
These are two separate issues, so let us tackle them 1-by-1 here.

Re: 1, which I think is the bigger issue, it turns out this is happening only in `1.2` and not `1.1` or before. In `1.2`, the indexing process was modified a little bit to ignore generated English APIs and instead focus on manually written Chinese API pages. This probably had an ill-effect on the index - possibly including some bad terms. Investigating the indexes now.

**Comment by varunarora** [comment]
Adding more notes here: the `invertedIndex` in `1.1` was about ~6.5k terms big, but in `1.2`, this bumped to 10k. Both for chinese. This is particularly interesting because in `1.2`, it doesn't index the English API pages, which should traditionally have been the biggest parts of the index. Hmm... interesting...

**Comment by varunarora** [comment]
Okay this didn't take too long to find the culprit. The keys on the `invertedIndex` are extremely long. Will try to fix this. Not at all surprised by the horrendous performance anymore.

**Comment by varunarora** [comment]
@shanyi15 What is the right format the user wants for the abstract?

**Comment by shanyi15** [comment]
I guess they means this symbol
![image](https://user-images.githubusercontent.com/35982308/50127060-73ae2800-02aa-11e9-937b-9b442da2e582.png)
