### ISSUE TITLE
Separate or remove doc_theme from Paddle repo

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/PaddlePaddle.org#83]
Can you separate or remove [doc_theme](https://github.com/PaddlePaddle/Paddle/tree/develop/doc_theme) from Paddle repo after merging your new document design?

**Comment by varunarora** [comment]
@luotao1 We shall gladly do that!

**Comment by varunarora** [comment]
@luotao1 We have decided not to touch the dir structure of Paddle repo for now (apart from other things, based on our conversation with @wangkuiyi, `doc`'s home will remain the `Paddle` repo). So we wouldn't be touching this for now at least. So unless someone in the core team (non-paddlepaddle.org) people feel confident around this, I am afraid it's going to hang around a little longer :(

**Comment by luotao1** [comment]
`doc_theme/` is independent with `doc/`, which is not maintained by Paddle core team, it contains just some css and js. Do you mean that you will maintain the design style of `doc`?

**Comment by varunarora** [comment]
Aha! Thanks for that clarification.

Yeah we are going to maintain the styling of the rendering of `doc` in PaddlePaddle.org (we are unifying the styling of all the different content repos there). That said, because `doc` needs to still be rendered independently when people pull the platform without using paddlepaddle.org, it would still need its CSS and JS and templating to be managed.

@wangkuiyi What's your opinion on how styling and interaction around `doc`, when distributed not through paddlepaddle.org, should be managed?

**Comment by cs2be** [comment]
No longer using doc_theme, we are now stripping the content of each HTML and applying a unified style
