### ISSUE TITLE
shorten the doc url

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/PaddlePaddle.org#84]
In new design, the document url likes : http://staging.paddlepaddle.org/documentation/develop/en/html/api/index_en.html

Currently, the same url is:
http://doc.paddlepaddle.org/develop/doc/api/index_en.html

'develop/doc' is shorter than 'documentation/develop/en/html/'

**Comment by varunarora** [comment]
You are 100% correct, @luotao1.

So lets look at each piece of the path we have one-by-one:

- We open with `/documentation/` because we no longer have the subdomain `doc.`. So we need a root reference. We could hypothetically make the version (in this case, `develop`) a parent of the `documentation`, but that might mean that `paddlepaddle.org/documentation` (or `paddlepaddle.org/doc`) needs to become `paddlepaddle.org/develop/documentation`. It's a design choice, and we are totally open to all ideas. I also think that URLs are really important to understand the contents of the page - so at the expense of URL brevity, I personally prefer a full word like `documentation` instead of an abbreviation or acronym. Again, design choice. 

- Since we were using the generated tree structure of Sphinx (in that it splits it into two dirs `en` and `cn`), we need to have `../en/..` in the path. Having the language in the path is a very common practice for the URL design world, so we don't mind that convention.

- `/html` is there because we didn't script moving the internals of the `en` and `cn` dirs. Since we hacking the URL routing on the various documentation contents, this was unfortunately an artifact of that. So you are completely right. As and when we reorganize and refactor our scripting to transform raw documentation outputs to something consistent, we shall take care of this.

Thanks for being so attentive the details, @luotao1. Appreciate all the insight.

**Comment by luotao1** [comment]
Thanks very much for your detail explanation!

- @llxxxll What do you think about `documentation` or `doc` ?
-  I agree with `../en/..` in the path. Now we use `doc_cn` to present `doc/cn/html`. 
- Expect to see that you can script moving the `/html` later. Our related code is in [build_doc.sh](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/travis/build_doc.sh#L56).

**Comment by 4luojing** [comment]
`documentation ` the description will be more accurate

**Comment by llxxxll** [comment]
`documentation ` the description will be more accurate

**Comment by varunarora** [comment]
URLs have been shorter and consistent for a while, so closing this.
